language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t lthom-docker-react -f DockerFile.dev . 

  script:
    - docker run  -e CI=true lthom-docker-react npm run test